### ISSUE TITLE
signature mismatch

### ISSUE THREAD

**Issue by fabsi88** [vibe-aws/vibe-aws#1]
Hey,
I've tried to use your lib and got an signature mismatch.(`InvalidSignatureException`) 
`
json: {
	"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\naccept-encoding:gzip, deflate\nconnection:\ncontent-type:application/x-amz-json-1.0\nhost:dynamodb.eu-central-1.amazonaws.com\nuser-agent:vibe.d/0.7.30 (HTTPClient, +http://vibed.org/)\nx-amz-date:20170112T195713Z\nx-amz-target:DynamoDB_20120810.PutItem\n\naccept-encoding;connection;content-type;host;user-agent;x-amz-date;x-amz-target\nd......06'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170112T195713Z\n20170112/eu-central-1/dynamodb/aws4_request\nb30.....fa6'\n",
`

I've shortened the hash for better reading.

Do you have any idea what causes this? Could you reproduce it?

**Comment by rix0rrr** [comment]
Sorry to hear that. I'm not in a position to test this easily any more on my own right now, unfortunately.

If you post the entire error message, I might be able to help and figure out what went wrong. Obviously, it's something in the signing, but there are a couple of steps to it and I need more information to determine what went wrong.

**Comment by fabsi88** [comment]
got it self fixed - there was a error in the headers. I will look further into this weekend and open a pull request.

**Comment by extrawurst** [comment]
seem like vibe.d simply started using keep-alive connections by default at some point and there seems to be an issue with adding 'connection' to the singned headers: 
https://github.com/inreachventures/aws-signing-request-interceptor/issues/20

**Comment by extrawurst** [comment]
here is the related PR to fix this:
https://github.com/rix0rrr/vibe-aws/pull/2

**Comment by rix0rrr** [comment]
Merged. Thanks!
