### ISSUE TITLE
future of the lib

### ISSUE THREAD

**Issue by extrawurst** [vibe-aws/vibe-aws#3]
ok we would like to know how to proceed from here. we want to make use of this lib. as we did with the last pullrequest we will also help with maintaining it. currently it is not clear how to get a clean version into dub though. your library is not in the dub registry.
we made your version working in regards to dynamoDB now.

There is a fork that added kinesis: https://github.com/yannick/vibe-aws (also not on dub)
and then there is a fork of THAT fork: https://github.com/tamediadigital/vibe-s3 (that is on dub)
The last fork ditched dynamoDB unfortunately :(

Perfect world i guess would be to split the whole signing and stuff into a separate package and have kinesis, dynamoDB and s3 in seperate packages depending on it - this requires a lot of effort on all ends though

**Comment by rix0rrr** [comment]
Hi Extrawurst,

To be honest, I've kind of lost the need for this project, as I've hopped fully onto the Rust bandwagon, and chances that I'll be doing D in the future are slim.

I'll happily turn over ownership of the project to you, if you want it, in whatever way you deem appropriate.

**Comment by fabsi88** [comment]
Hey @rix0rrr ,

please turn over ownership to our org https://github.com/vibe-aws . This is a org of @Extrawurst  and me. Thank you very much for the work on this - saved us a lot of time :)

**Comment by rix0rrr** [comment]
Done. Enjoy!

**Comment by extrawurst** [comment]
Thank you, we will take good care of it ;)
